### ISSUE TITLE
local custom_ui

### ISSUE THREAD

**Issue by MikeMannox** [robwolff3/homeassistant-config#2]
Can you please include the directories and files in your `frontend:  /local/custom_ui`

I would like to see how to set these up correctly as it seems you have it working

```
frontend:
  javascript_version: es5
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles.html
```
